# Generated by Django 5.1.7 on 2025-03-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="bankloan",
            fields=[
                (
                    "cust_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("loan_ID", models.IntegerField()),
                ("loan_type", models.CharField(max_length=50)),
                ("loan_amnt", models.FloatField()),
                ("cust_acno", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Loan_DB",
        ),
    ]
